/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUURLComponents.h"

@interface MOZUOrderURLComponents : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**
Resource Url Components for getOrders
@param startIndex 
@param pageSize Used to create paged results from a query. Specifies the number of results to display on each page. Maximum: 200.
@param sortBy 
@param filter A set of expressions that consist of a field, operator, and value and represent search parameter syntax when filtering results of a query. You can filter an order's search results by any of its properties, including status, contact information, or total. Valid operators include equals (eq), does not equal (ne), greater than (gt), less than (lt), greater than or equal to (ge), less than or equal to (le), starts with (sw), or contains (cont). <b>For example - "filter=Status+eq+Submitted"</b>
@param q 
@param qLimit 
*/
+ (MOZUURLComponents *)URLComponentsForGetOrdersOperationWithStartIndex:(NSNumber *)startIndex pageSize:(NSNumber *)pageSize sortBy:(NSString *)sortBy filter:(NSString *)filter q:(NSString *)q qLimit:(NSNumber *)qLimit;

/**
Resource Url Components for getAvailableActions
@param orderId Unique identifier of the available order actions to get.
*/
+ (MOZUURLComponents *)URLComponentsForGetAvailableActionsOperationWithOrderId:(NSString *)orderId;

/**
Resource Url Components for getTaxableOrders
@param orderId 
*/
+ (MOZUURLComponents *)URLComponentsForGetTaxableOrdersOperationWithOrderId:(NSString *)orderId;

/**
Resource Url Components for getOrder
@param orderId Unique identifier of the order details to get.
@param draft 
*/
+ (MOZUURLComponents *)URLComponentsForGetOrderOperationWithOrderId:(NSString *)orderId draft:(NSNumber *)draft;


//
#pragma mark -
#pragma mark POST Operations
#pragma mark -
//

/**
Resource Url Components for createOrder
*/
+ (MOZUURLComponents *)URLComponentsForCreateOrderOperation;

/**
Resource Url Components for createOrderFromCart
@param cartId Unique identifier of the cart. This is the original cart ID expressed as a GUID.
*/
+ (MOZUURLComponents *)URLComponentsForCreateOrderFromCartOperationWithCartId:(NSString *)cartId;

/**
Resource Url Components for performOrderAction
@param orderId Unique identifier of the order.
*/
+ (MOZUURLComponents *)URLComponentsForPerformOrderActionOperationWithOrderId:(NSString *)orderId;


//
#pragma mark -
#pragma mark PUT Operations
#pragma mark -
//

/**
Resource Url Components for updateOrderDiscount
@param orderId 
@param discountId 
@param updateMode 
@param version 
*/
+ (MOZUURLComponents *)URLComponentsForUpdateOrderDiscountOperationWithOrderId:(NSString *)orderId discountId:(NSInteger)discountId updateMode:(NSString *)updateMode version:(NSString *)version;

/**
Resource Url Components for deleteOrderDraft
@param orderId 
@param version 
*/
+ (MOZUURLComponents *)URLComponentsForDeleteOrderDraftOperationWithOrderId:(NSString *)orderId version:(NSString *)version;

/**
Resource Url Components for changeOrderUserId
@param orderId Unique identifier of the order to change.
*/
+ (MOZUURLComponents *)URLComponentsForChangeOrderUserIdOperationWithOrderId:(NSString *)orderId;

/**
Resource Url Components for updateOrder
@param orderId Unique identifier of the order to update.
@param updateMode 
@param version 
*/
+ (MOZUURLComponents *)URLComponentsForUpdateOrderOperationWithOrderId:(NSString *)orderId updateMode:(NSString *)updateMode version:(NSString *)version;


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//



@end