/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUURLComponents.h"

@interface MOZUReturnURLComponents : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**
Resource Url Components for getReturns
@param startIndex When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with a PageSize of 25, to get the 51st through the 75th items, use startIndex=3.
@param pageSize The number of results to display on each page when creating paged results from a query. The maximum value is 200.
@param sortBy The property by which to sort results and whether the results appear in ascending (a-z) order, represented by ASC or in descending (z-a) order, represented by DESC. The sortBy parameter follows an available property. For example: "sortBy=productCode+asc"
@param filter A set of expressions that consist of a field, operator, and value and represent search parameter syntax when filtering results of a query. Valid operators include equals (eq), does not equal (ne), greater than (gt), less than (lt), greater than or equal to (ge), less than or equal to (le), starts with (sw), or contains (cont). For example - "filter=IsDisplayed+eq+true"
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForGetReturnsOperationWithStartIndex:(NSNumber *)startIndex pageSize:(NSNumber *)pageSize sortBy:(NSString *)sortBy filter:(NSString *)filter responseFields:(NSString *)responseFields;

/**
Resource Url Components for getAvailableReturnActions
@param returnId Unique identifier of the return whose items you want to get.
*/
+ (MOZUURLComponents *)URLComponentsForGetAvailableReturnActionsOperationWithReturnId:(NSString *)returnId;

/**
Resource Url Components for getReturnItem
@param returnId Unique identifier of the return whose items you want to get.
@param returnItemId Unique identifier of the return item whose details you want to get.
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForGetReturnItemOperationWithReturnId:(NSString *)returnId returnItemId:(NSString *)returnItemId responseFields:(NSString *)responseFields;

/**
Resource Url Components for getReturnItems
@param returnId Unique identifier of the return whose items you want to get.
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForGetReturnItemsOperationWithReturnId:(NSString *)returnId responseFields:(NSString *)responseFields;

/**
Resource Url Components for getAvailablePaymentActionsForReturn
@param returnId Unique identifier of the return whose items you want to get.
@param paymentId Unique identifier of the payment for which to perform the action.
*/
+ (MOZUURLComponents *)URLComponentsForGetAvailablePaymentActionsForReturnOperationWithReturnId:(NSString *)returnId paymentId:(NSString *)paymentId;

/**
Resource Url Components for getPayment
@param returnId Unique identifier of the return whose items you want to get.
@param paymentId Unique identifier of the payment for which to perform the action.
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForGetPaymentOperationWithReturnId:(NSString *)returnId paymentId:(NSString *)paymentId responseFields:(NSString *)responseFields;

/**
Resource Url Components for getPayments
@param returnId Unique identifier of the return whose items you want to get.
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForGetPaymentsOperationWithReturnId:(NSString *)returnId responseFields:(NSString *)responseFields;

/**
Resource Url Components for getReturn
@param returnId Unique identifier of the return whose items you want to get.
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForGetReturnOperationWithReturnId:(NSString *)returnId responseFields:(NSString *)responseFields;

/**
Resource Url Components for getReasons
@param responseFields A list or array of fields returned for a call. These fields may be customized and may be used for various types of data calls in Mozu. For example, responseFields are returned for retrieving or updating attributes, carts, and messages in Mozu.
*/
+ (MOZUURLComponents *)URLComponentsForGetReasonsOperationWithResponseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark POST Operations
#pragma mark -
//

/**
Resource Url Components for createReturn
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForCreateReturnOperationWithResponseFields:(NSString *)responseFields;

/**
Resource Url Components for createReturnItem
@param returnId Unique identifier of the return whose items you want to get.
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForCreateReturnItemOperationWithReturnId:(NSString *)returnId responseFields:(NSString *)responseFields;

/**
Resource Url Components for performPaymentActionForReturn
@param returnId Unique identifier of the return whose items you want to get.
@param paymentId Unique identifier of the payment for which to perform the action.
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForPerformPaymentActionForReturnOperationWithReturnId:(NSString *)returnId paymentId:(NSString *)paymentId responseFields:(NSString *)responseFields;

/**
Resource Url Components for createPaymentActionForReturn
@param returnId Unique identifier of the return whose items you want to get.
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForCreatePaymentActionForReturnOperationWithReturnId:(NSString *)returnId responseFields:(NSString *)responseFields;

/**
Resource Url Components for performReturnActions
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForPerformReturnActionsOperationWithResponseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark PUT Operations
#pragma mark -
//

/**
Resource Url Components for updateReturn
@param returnId Unique identifier of the return whose items you want to get.
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForUpdateReturnOperationWithReturnId:(NSString *)returnId responseFields:(NSString *)responseFields;

/**
Resource Url Components for resendReturnEmail
*/
+ (MOZUURLComponents *)URLComponentsForResendReturnEmailOperation;


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**
Resource Url Components for deleteOrderItem
@param returnId Unique identifier of the return whose items you want to get.
@param returnItemId Unique identifier of the return item whose details you want to get.
*/
+ (MOZUURLComponents *)URLComponentsForDeleteOrderItemOperationWithReturnId:(NSString *)returnId returnItemId:(NSString *)returnItemId;

/**
Resource Url Components for deleteReturn
@param returnId Unique identifier of the return whose items you want to get.
*/
+ (MOZUURLComponents *)URLComponentsForDeleteReturnOperationWithReturnId:(NSString *)returnId;



@end