
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "MOZUClient.h"
#import "MOZUDocumentCollection.h"
#import "MOZUDocument.h"


@interface MOZUDocumentClient : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**
Retrieve the content associated with a document, such as a product image or PDF specifications file, by supplying the document ID.
@param documentId Unique identifier for a document, used by content and document calls. Document IDs are associated with document types, document type lists, sites, and tenants.
@param documentListName Name of content documentListName to delete
*/

+ (MOZUClient *)clientForGetDocumentContentOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode documentListName:(NSString *)documentListName documentId:(NSString *)documentId;

/**
Performs transformations on a document. For example, resizing an image.
@param crop Crops the image based on the specified coordinates. The reference point for positive coordinates is the top-left corner of the image, and the reference point for negative coordinates is the bottom-right corner of the image.Usage: Example:  removes 10 pixels from all edges of the image.  leaves the image uncropped.
@param documentId Unique identifier for a document, used by content and document calls. Document IDs are associated with document types, document type lists, sites, and tenants.
@param documentListName Name of content documentListName to delete
@param height Specifies an exact height dimension for the image, in pixels.
@param max Specifies a pixel limitation for the largest side of an image.
@param maxHeight Specifies a pixel limitation for the height of the image, preserving the aspect ratio if the image needs resizing.
@param maxWidth Specifies a pixel limitation for the width of the image, preserving the aspect ratio if the image needs resizing.
@param quality Adjusts the image compression. Accepts values from 0-100, where 100 = highest quality, least compression.
@param width Specifies an exact width dimension for the image, in pixels.
*/

+ (MOZUClient *)clientForTransformDocumentContentOperationWithDocumentListName:(NSString *)documentListName documentId:(NSString *)documentId width:(NSNumber *)width height:(NSNumber *)height max:(NSNumber *)max maxWidth:(NSNumber *)maxWidth maxHeight:(NSNumber *)maxHeight crop:(NSString *)crop quality:(NSNumber *)quality;

/**
Retrieves a document within the specified document list.
@param documentId Unique identifier for a document, used by content and document calls. Document IDs are associated with document types, document type lists, sites, and tenants.
@param documentListName Name of content documentListName to delete
@param includeInactive Include inactive content.
@param responseFields Use this field to include those fields which are not included by default.
*/

+ (MOZUClient *)clientForGetDocumentOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode documentListName:(NSString *)documentListName documentId:(NSString *)documentId includeInactive:(NSNumber *)includeInactive responseFields:(NSString *)responseFields;

/**
Retrieves a collection of documents according to any filter and sort criteria.
@param documentListName Name of content documentListName to delete
@param filter A set of filter expressions representing the search parameters for a query: eq=equals, ne=not equals, gt=greater than, lt = less than or equals, gt = greater than or equals, lt = less than or equals, sw = starts with, or cont = contains. Optional.
@param includeInactive Include inactive content.
@param pageSize The number of results to display on each page when creating paged results from a query. The maximum value is 200.
@param responseFields Use this field to include those fields which are not included by default.
@param sortBy The property by which to sort results and whether the results appear in ascending (a-z) order, represented by ASC or in descending (z-a) order, represented by DESC. The sortBy parameter follows an available property. For example: "sortBy=productCode+asc"
@param startIndex When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with a PageSize of 25, to get the 51st through the 75th items, use startIndex=3.
*/

+ (MOZUClient *)clientForGetDocumentsOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode documentListName:(NSString *)documentListName filter:(NSString *)filter sortBy:(NSString *)sortBy pageSize:(NSNumber *)pageSize startIndex:(NSNumber *)startIndex includeInactive:(NSNumber *)includeInactive responseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

/**
Creates a new document in an defined document list.
@param body The document properties that define the content used by the content management system (CMS).
@param documentListName Name of content documentListName to delete
@param responseFields Use this field to include those fields which are not included by default.
*/

+ (MOZUClient *)clientForCreateDocumentOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode body:(MOZUDocument *)body documentListName:(NSString *)documentListName responseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

/**
Updates the binary data or content associated with a document, such as a product image or PDF specifications file, by supplying the document ID.
@param body Data stream that delivers information. Used to input and output data.
@param documentId Unique identifier for a document, used by content and document calls. Document IDs are associated with document types, document type lists, sites, and tenants.
@param documentListName Name of content documentListName to delete
*/

+ (MOZUClient *)clientForUpdateDocumentContentOperationWithBody:(NSInputStream *)body documentListName:(NSString *)documentListName documentId:(NSString *)documentId;

/**
Updates a document in a document list.
@param body The document properties that define the content used by the content management system (CMS).
@param documentId Unique identifier for a document, used by content and document calls. Document IDs are associated with document types, document type lists, sites, and tenants.
@param documentListName Name of content documentListName to delete
@param responseFields Use this field to include those fields which are not included by default.
*/

+ (MOZUClient *)clientForUpdateDocumentOperationWithBody:(MOZUDocument *)body documentListName:(NSString *)documentListName documentId:(NSString *)documentId responseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**
Deletes a specific document based on the specified document ID.
@param documentId Unique identifier for a document, used by content and document calls. Document IDs are associated with document types, document type lists, sites, and tenants.
@param documentListName Name of content documentListName to delete
*/

+ (MOZUClient *)clientForDeleteDocumentOperationWithDocumentListName:(NSString *)documentListName documentId:(NSString *)documentId;

/**
Deletes the content associated with a document, such as a product image or PDF specification, by supplying the document ID.
@param documentId Unique identifier for a document, used by content and document calls. Document IDs are associated with document types, document type lists, sites, and tenants.
@param documentListName Name of content documentListName to delete
*/

+ (MOZUClient *)clientForDeleteDocumentContentOperationWithDocumentListName:(NSString *)documentListName documentId:(NSString *)documentId;



@end