/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUURL.h"

@interface MOZUCartItemURL : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**
Resource Url for getCartItems
*/
+(MOZUURL*)URLForGetCartItemsOperation;

/**
Resource Url for getCartItem
@param cartItemId Identifier of the cart item to retrieve.
*/
+(MOZUURL*)URLForGetCartItemOperationWithCartItemId:(NSString*)cartItemId;


//
#pragma mark -
#pragma mark POST Operations
#pragma mark -
//

/**
Resource Url for addItemToCart
*/
+(MOZUURL*)URLForAddItemToCartOperation;


//
#pragma mark -
#pragma mark PUT Operations
#pragma mark -
//

/**
Resource Url for updateCartItem
@param cartItemId Identifier of the cart item to update.
*/
+(MOZUURL*)URLForUpdateCartItemOperationWithCartItemId:(NSString*)cartItemId;

/**
Resource Url for updateCartItemQuantity
@param cartItemId Identifier of the cart item to update quantity.
@param quantity The number of cart items in the shopper's active cart.
*/
+(MOZUURL*)URLForUpdateCartItemQuantityOperationWithCartItemId:(NSString*)cartItemId quantity:(NSInteger)quantity;


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**
Resource Url for removeAllCartItems
*/
+(MOZUURL*)URLForRemoveAllCartItemsOperation;

/**
Resource Url for deleteCartItem
@param cartItemId Identifier of the cart item to delete.
*/
+(MOZUURL*)URLForDeleteCartItemOperationWithCartItemId:(NSString*)cartItemId;



@end