
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"



@protocol MOZUFulfillmentType
@end


/**
	Properties of a method used to fulfill items for an order. Fulfillment types are system-supplied, and include direct ship (DS) or in-store pickup (SP) at this time.
*/
@interface MOZUFulfillmentType : JSONModel<MOZUFulfillmentType>

/**
The system-supplied code that identifies the fulfillment type, which is "DS" for direct ship or "SP" for in-store pickup.
*/
@property(nonatomic) NSString *code;

/**
The system-supplied name of the fulfillment type, which is "Direct Ship" or "In Store Pickup".
*/
@property(nonatomic) NSString *name;

@end

