
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "MOZUProduct.h"



@protocol MOZUOrderItem
@end


/**
	Mozu.PaymentService.Contracts.OrderItem ApiType DOCUMENT_HERE 
*/
@interface MOZUOrderItem : JSONModel<MOZUOrderItem>

/**
Unique identifier of the source product property. For a product field it will be the name of the field. For a product attribute it will be the Attribute FQN. 
*/
@property(nonatomic) NSString * id;

/**
The specified quantity of objects and items. This property is used for numerous object types including products, options, components within a product bundle, cart and order items, returned items, shipping line items, items in a digital product. and items associated with types and reservations.
*/
@property(nonatomic) NSInteger quantity;

/**
Mozu.PaymentService.Contracts.OrderItem taxAmount ApiTypeMember DOCUMENT_HERE 
*/
@property(nonatomic) NSNumber * taxAmount;

/**
Mozu.PaymentService.Contracts.OrderItem totalAmount ApiTypeMember DOCUMENT_HERE 
*/
@property(nonatomic) NSNumber * totalAmount;

/**
Properties of the price per unit of a product, associated with cart and order items. This price is not used for wish lists at this time.
*/
@property(nonatomic) NSNumber * unitPrice;

/**
The properties of a product, referenced and used by carts, orders, wish lists, and returns.
*/
@property(nonatomic) MOZUProduct *product;

@end

