
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"



@protocol MOZUProduct
@end


/**
	The properties of a product, referenced and used by carts, orders, wish lists, and returns.
*/
@interface MOZUProduct : JSONModel<MOZUProduct>

/**
The unique, user-defined  product code of a product, used throughout Mozu to reference and associate to a product.
*/
@property(nonatomic) NSString * productCode;

/**
The name of the product that represents a line item in a taxable order or product bundle.
*/
@property(nonatomic) NSString * productName;

@end

