
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUDocumentDraftSummaryClient.h"
#import "MOZUDocumentDraftSummaryURLComponents.h"
#import "MozuDocumentDraftSummaryPagedCollection.h"


@implementation MOZUDocumentDraftSummaryClient

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

+ (MOZUClient *)clientForListDocumentDraftSummariesOperationWithPageSize:(NSNumber *)pageSize startIndex:(NSNumber *)startIndex documentLists:(NSString *)documentLists responseFields:(NSString *)responseFields {
	id url = [MOZUDocumentDraftSummaryURLComponents URLComponentsForListDocumentDraftSummariesOperationWithPageSize:pageSize startIndex:startIndex documentLists:documentLists responseFields:responseFields];
	id verb = @"GET";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];


	client.JSONParser = ^id(NSString *jsonResult) {
		return [[MOZUDocumentDraftSummaryPagedCollection alloc] initWithString:jsonResult error:nil];
	};

	return client;
}


//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

+ (MOZUClient *)clientForDeleteDocumentDraftsOperationWithBody:(NSArray *)body documentLists:(NSString *)documentLists {
	id url = [MOZUDocumentDraftSummaryURLComponents URLComponentsForDeleteDocumentDraftsOperationWithDocumentLists:documentLists];
	id verb = @"POST";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	client.body = body;
	return client;
}


//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

+ (MOZUClient *)clientForPublishDocumentsOperationWithBody:(NSArray *)body documentLists:(NSString *)documentLists {
	id url = [MOZUDocumentDraftSummaryURLComponents URLComponentsForPublishDocumentsOperationWithDocumentLists:documentLists];
	id verb = @"PUT";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	client.body = body;
	return client;
}


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//



@end