
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "MOZUClient.h"
#import "MOZUAPIContext.h"

#import "MOZUSoftAllocation.h"
#import "MOZUProductReservation.h"
#import "MOZUSoftAllocationCollection.h"


@interface MOZUSoftAllocationResource : NSObject


@property(readonly, nonatomic) MOZUAPIContext * apiContext;

-(id)initWithAPIContext:(MOZUAPIContext *)apiContext;

-(id)cloneWithAPIContextModification:(MOZUAPIContextModificationBlock)apiContextModification;

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**

@param filter 
@param pageSize 
@param responseFields 
@param sortBy 
@param startIndex 
*/

- (void)softAllocationsWithStartIndex:(NSNumber *)startIndex pageSize:(NSNumber *)pageSize sortBy:(NSString *)sortBy filter:(NSString *)filter responseFields:(NSString *)responseFields completionHandler:(void(^)(MOZUSoftAllocationCollection *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;
/**

@param responseFields 
@param softAllocationId 
*/

- (void)softAllocationWithSoftAllocationId:(NSInteger)softAllocationId responseFields:(NSString *)responseFields completionHandler:(void(^)(MOZUSoftAllocation *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;

//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

/**

@param body 
*/

- (void)addSoftAllocationsWithBody:(NSArray<MOZUSoftAllocation> *)body completionHandler:(void(^)(NSArray<MOZUSoftAllocation> *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;
/**

@param body 
*/

- (void)convertToProductReservationWithBody:(NSArray<MOZUSoftAllocation> *)body completionHandler:(void(^)(NSArray<MOZUProductReservation> *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;

//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

/**

@param body 
*/

- (void)updateSoftAllocationsWithBody:(NSArray<MOZUSoftAllocation> *)body completionHandler:(void(^)(NSArray<MOZUSoftAllocation> *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;

//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**

@param softAllocationId 
*/

- (void)deleteSoftAllocationWithSoftAllocationId:(NSInteger)softAllocationId completionHandler:(void(^)(MOZUAPIError *error, NSHTTPURLResponse *response))handler
;


@end