
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "MOZUClient.h"
#import "MOZUAPIContext.h"

#import "MOZUSearchSettings.h"
#import "MOZUSearchTuningRuleCollection.h"
#import "MOZUSearchTuningRule.h"
#import "MOZUSearchTuningRuleSortFields.h"


@interface MOZUSearchResource : NSObject


@property(readonly, nonatomic) MOZUAPIContext * apiContext;

-(id)initWithAPIContext:(MOZUAPIContext *)apiContext;

-(id)cloneWithAPIContextModification:(MOZUAPIContextModificationBlock)apiContextModification;

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**
admin-search Get GetSearchTuningRule description DOCUMENT_HERE 
@param responseFields A list or array of fields returned for a call. These fields may be customized and may be used for various types of data calls in Mozu. For example, responseFields are returned for retrieving or updating attributes, carts, and messages in Mozu.
@param searchTuningRuleCode 
*/

- (void)searchTuningRuleWithSearchTuningRuleCode:(NSString *)searchTuningRuleCode responseFields:(NSString *)responseFields completionHandler:(void(^)(MOZUSearchTuningRule *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;
/**
admin-search Get GetSearchTuningRules description DOCUMENT_HERE 
@param filter A set of filter expressions representing the search parameters for a query: eq=equals, ne=not equals, gt=greater than, lt = less than or equals, gt = greater than or equals, lt = less than or equals, sw = starts with, or cont = contains. Optional.
@param pageSize The number of results to display on each page when creating paged results from a query. The amount is divided and displayed on the `pageCount `amount of pages. The default is 20 and maximum value is 200 per page.
@param responseFields A list or array of fields returned for a call. These fields may be customized and may be used for various types of data calls in Mozu. For example, responseFields are returned for retrieving or updating attributes, carts, and messages in Mozu.
@param sortBy The element to sort the results by and the channel in which the results appear. Either ascending (a-z) or descending (z-a) channel. Optional.
@param startIndex When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with a `pageSize `of 25, to get the 51st through the 75th items, use `startIndex=3`.
*/

- (void)searchTuningRulesWithStartIndex:(NSNumber *)startIndex pageSize:(NSNumber *)pageSize sortBy:(NSString *)sortBy filter:(NSString *)filter responseFields:(NSString *)responseFields completionHandler:(void(^)(MOZUSearchTuningRuleCollection *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;
/**

*/

- (void)searchTuningRuleSortFieldsWithCompletionHandler:(void(^)(NSInputStream *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;
/**
Get site search settings
@param responseFields A list or array of fields returned for a call. These fields may be customized and may be used for various types of data calls in Mozu. For example, responseFields are returned for retrieving or updating attributes, carts, and messages in Mozu.
*/

- (void)settingsWithResponseFields:(NSString *)responseFields completionHandler:(void(^)(MOZUSearchSettings *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;

//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

/**
admin-search Post AddSearchTuningRule description DOCUMENT_HERE 
@param body Mozu.ProductAdmin.Contracts.Search.SearchTuningRule ApiType DOCUMENT_HERE 
@param responseFields A list or array of fields returned for a call. These fields may be customized and may be used for various types of data calls in Mozu. For example, responseFields are returned for retrieving or updating attributes, carts, and messages in Mozu.
*/

- (void)addSearchTuningRuleWithBody:(MOZUSearchTuningRule *)body responseFields:(NSString *)responseFields completionHandler:(void(^)(MOZUSearchTuningRule *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;
/**

@param body 
*/

- (void)updateSearchTuningRuleSortFieldsWithBody:(MOZUSearchTuningRuleSortFields *)body completionHandler:(void(^)(MOZUAPIError *error, NSHTTPURLResponse *response))handler
;

//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

/**
admin-search Put UpdateSearchTuningRule description DOCUMENT_HERE 
@param body Mozu.ProductAdmin.Contracts.Search.SearchTuningRule ApiType DOCUMENT_HERE 
@param responseFields A list or array of fields returned for a call. These fields may be customized and may be used for various types of data calls in Mozu. For example, responseFields are returned for retrieving or updating attributes, carts, and messages in Mozu.
@param searchTuningRuleCode 
*/

- (void)updateSearchTuningRuleWithBody:(MOZUSearchTuningRule *)body searchTuningRuleCode:(NSString *)searchTuningRuleCode responseFields:(NSString *)responseFields completionHandler:(void(^)(MOZUSearchTuningRule *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;
/**
Adds or Updates (Upsert) the Search Settings for a specific site
@param body The settings to control product search and indexing behavior.
@param responseFields A list or array of fields returned for a call. These fields may be customized and may be used for various types of data calls in Mozu. For example, responseFields are returned for retrieving or updating attributes, carts, and messages in Mozu.
*/

- (void)updateSettingsWithBody:(MOZUSearchSettings *)body responseFields:(NSString *)responseFields completionHandler:(void(^)(MOZUSearchSettings *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;

//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**
admin-search Delete DeleteSearchTuningRule description DOCUMENT_HERE 
@param searchTuningRuleCode 
*/

- (void)deleteSearchTuningRuleWithSearchTuningRuleCode:(NSString *)searchTuningRuleCode completionHandler:(void(^)(MOZUAPIError *error, NSHTTPURLResponse *response))handler
;


@end