/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUFacetURL.h"

@implementation MOZUFacetURL

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

+(MOZUURL*)URLForGetFacetOperationWithFacetId:(NSInteger)facetId validate:(NSNumber*)validate {
	NSString* template = @"/api/commerce/catalog/admin/facets/{facetId}?validate={validate}";
	NSDictionary* params = @{
		@"facetId" : @(facetId),
		@"validate" : validate,
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}

+(MOZUURL*)URLForGetFacetCategoryListOperationWithCategoryId:(NSInteger)categoryId includeAvailable:(NSNumber*)includeAvailable validate:(NSNumber*)validate {
	NSString* template = @"/api/commerce/catalog/admin/facets/category/{categoryId}?includAvaliable={includeAvailable}&validate={validate}";
	NSDictionary* params = @{
		@"categoryId" : @(categoryId),
		@"includeAvailable" : includeAvailable,
		@"validate" : validate,
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

+(MOZUURL*)URLForAddFacetOperation {
	NSString* template = @"/api/commerce/catalog/admin/facets/";
	NSDictionary* params = nil;

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

+(MOZUURL*)URLForUpdateFacetOperationWithFacetId:(NSInteger)facetId {
	NSString* template = @"/api/commerce/catalog/admin/facets/{facetId}";
	NSDictionary* params = @{
		@"facetId" : @(facetId),
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

+(MOZUURL*)URLForDeleteFacetByIdOperationWithFacetId:(NSInteger)facetId {
	NSString* template = @"/api/commerce/catalog/admin/facets/{facetId}";
	NSDictionary* params = @{
		@"facetId" : @(facetId),
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}



@end