/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUAdminFacetURLComponents.h"

@implementation MOZUAdminFacetURLComponents

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

+(MOZUURLComponents*)URLComponentsForGetFacetOperationWithFacetId:(NSInteger)facetId validate:(NSNumber*)validate {
	NSString* template = @"/api/commerce/catalog/admin/facets/{facetId}?validate={validate}";
	NSDictionary* params = @{
		@"facetId" : @(facetId),
		@"validate" : validate,
	};

	return [[MOZUURLComponents alloc] initWithTemplate:template parameters:params location:MOZUTenantPod useSSL:NO];
}

+(MOZUURLComponents*)URLComponentsForGetFacetCategoryListOperationWithCategoryId:(NSInteger)categoryId includeAvailable:(NSNumber*)includeAvailable validate:(NSNumber*)validate {
	NSString* template = @"/api/commerce/catalog/admin/facets/category/{categoryId}?includAvaliable={includeAvailable}&validate={validate}";
	NSDictionary* params = @{
		@"categoryId" : @(categoryId),
		@"includeAvailable" : includeAvailable,
		@"validate" : validate,
	};

	return [[MOZUURLComponents alloc] initWithTemplate:template parameters:params location:MOZUTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

+(MOZUURLComponents*)URLComponentsForAddFacetOperation {
	NSString* template = @"/api/commerce/catalog/admin/facets/";
	NSDictionary* params = nil;

	return [[MOZUURLComponents alloc] initWithTemplate:template parameters:params location:MOZUTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

+(MOZUURLComponents*)URLComponentsForUpdateFacetOperationWithFacetId:(NSInteger)facetId {
	NSString* template = @"/api/commerce/catalog/admin/facets/{facetId}";
	NSDictionary* params = @{
		@"facetId" : @(facetId),
	};

	return [[MOZUURLComponents alloc] initWithTemplate:template parameters:params location:MOZUTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

+(MOZUURLComponents*)URLComponentsForDeleteFacetByIdOperationWithFacetId:(NSInteger)facetId {
	NSString* template = @"/api/commerce/catalog/admin/facets/{facetId}";
	NSDictionary* params = @{
		@"facetId" : @(facetId),
	};

	return [[MOZUURLComponents alloc] initWithTemplate:template parameters:params location:MOZUTenantPod useSSL:NO];
}



@end