
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"



@protocol MOZUHttpStatus
@end


@interface MOZUHttpStatus : JSONModel<MOZUHttpStatus>

@property(nonatomic) NSIntegercode;

@property(nonatomic) NSString *name;

@end

