
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "MOZUAddress.h"



@protocol MOZUPricingTaxContext
@end


/**
	The tax properties associated with the order.
*/
@interface MOZUPricingTaxContext : JSONModel<MOZUPricingTaxContext>

/**
Unique identifier of the customer in Mozu, used to associate customers with data, orders, returns, and in-store credit.
*/
@property(nonatomic) NSString * customerId;

/**
Unique identifier of the tax context.
*/
@property(nonatomic) NSString * taxContextId;

/**
If the order is exempt from sales tax, the unique identifier of the tax exempt entity.
*/
@property(nonatomic) NSString * taxExemptId;

/**
The physical address orders are sent to as a shipping destination. This address may contain multiple lines, city, state/province, country, and zip/postal code. The destination is used to calculate shipping costs.
*/
@property(nonatomic) MOZUAddress *destinationAddress;

/**
The physical address from which the order or shipment will ship.
*/
@property(nonatomic) MOZUAddress *originAddress;

@end

