
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUProductVariationClient.h"
#import "MOZUProductVariationURLComponents.h"
#import "MozuProductVariationFixedPrice.h"
#import "MozuProductVariationDeltaPrice.h"
#import "MozuProductVariation.h"
#import "MozuProductVariationPagedCollection.h"
#import "MozuProductVariationCollection.h"


@implementation MOZUProductVariationClient

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

+ (MOZUClient *)clientForGetProductVariationLocalizedDeltaPricesOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode productCode:(NSString *)productCode variationKey:(NSString *)variationKey {
	id url = [MOZUProductVariationURLComponents URLComponentsForGetProductVariationLocalizedDeltaPricesOperationWithProductCode:productCode variationKey:variationKey];
	id verb = @"GET";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];


	client.JSONParser = ^id(NSString *jsonResult) {
		NSArray *jsonAsArray = [NSJSONSerialization JSONObjectWithData:[jsonResult dataUsingEncoding:NSUTF8StringEncoding] options:kNilOptions error:nil];
		return [MOZUProductVariationDeltaPrice arrayOfModelsFromDictionaries:jsonAsArray error:nil];
	};

	return client;
}

+ (MOZUClient *)clientForGetProductVariationLocalizedDeltaPriceOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode productCode:(NSString *)productCode variationKey:(NSString *)variationKey currencyCode:(NSString *)currencyCode responseFields:(NSString *)responseFields {
	id url = [MOZUProductVariationURLComponents URLComponentsForGetProductVariationLocalizedDeltaPriceOperationWithProductCode:productCode variationKey:variationKey currencyCode:currencyCode responseFields:responseFields];
	id verb = @"GET";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];


	client.JSONParser = ^id(NSString *jsonResult) {
		return [[MOZUProductVariationDeltaPrice alloc] initWithString:jsonResult error:nil];
	};

	return client;
}

+ (MOZUClient *)clientForGetProductVariationLocalizedPricesOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode productCode:(NSString *)productCode variationKey:(NSString *)variationKey {
	id url = [MOZUProductVariationURLComponents URLComponentsForGetProductVariationLocalizedPricesOperationWithProductCode:productCode variationKey:variationKey];
	id verb = @"GET";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];


	client.JSONParser = ^id(NSString *jsonResult) {
		NSArray *jsonAsArray = [NSJSONSerialization JSONObjectWithData:[jsonResult dataUsingEncoding:NSUTF8StringEncoding] options:kNilOptions error:nil];
		return [MOZUProductVariationFixedPrice arrayOfModelsFromDictionaries:jsonAsArray error:nil];
	};

	return client;
}

+ (MOZUClient *)clientForGetProductVariationLocalizedPriceOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode productCode:(NSString *)productCode variationKey:(NSString *)variationKey currencyCode:(NSString *)currencyCode responseFields:(NSString *)responseFields {
	id url = [MOZUProductVariationURLComponents URLComponentsForGetProductVariationLocalizedPriceOperationWithProductCode:productCode variationKey:variationKey currencyCode:currencyCode responseFields:responseFields];
	id verb = @"GET";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];


	client.JSONParser = ^id(NSString *jsonResult) {
		return [[MOZUProductVariationFixedPrice alloc] initWithString:jsonResult error:nil];
	};

	return client;
}

+ (MOZUClient *)clientForGetProductVariationOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode productCode:(NSString *)productCode variationKey:(NSString *)variationKey responseFields:(NSString *)responseFields {
	id url = [MOZUProductVariationURLComponents URLComponentsForGetProductVariationOperationWithProductCode:productCode variationKey:variationKey responseFields:responseFields];
	id verb = @"GET";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];


	client.JSONParser = ^id(NSString *jsonResult) {
		return [[MOZUProductVariation alloc] initWithString:jsonResult error:nil];
	};

	return client;
}

+ (MOZUClient *)clientForGetProductVariationsOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode productCode:(NSString *)productCode startIndex:(NSNumber *)startIndex pageSize:(NSNumber *)pageSize sortBy:(NSString *)sortBy filter:(NSString *)filter responseFields:(NSString *)responseFields {
	id url = [MOZUProductVariationURLComponents URLComponentsForGetProductVariationsOperationWithProductCode:productCode startIndex:startIndex pageSize:pageSize sortBy:sortBy filter:filter responseFields:responseFields];
	id verb = @"GET";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];


	client.JSONParser = ^id(NSString *jsonResult) {
		return [[MOZUProductVariationPagedCollection alloc] initWithString:jsonResult error:nil];
	};

	return client;
}


//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

+ (MOZUClient *)clientForAddProductVariationLocalizedDeltaPriceOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode body:(MOZUProductVariationDeltaPrice *)body productCode:(NSString *)productCode variationKey:(NSString *)variationKey responseFields:(NSString *)responseFields {
	id url = [MOZUProductVariationURLComponents URLComponentsForAddProductVariationLocalizedDeltaPriceOperationWithProductCode:productCode variationKey:variationKey responseFields:responseFields];
	id verb = @"POST";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];

	client.body = body;

	client.JSONParser = ^id(NSString *jsonResult) {
		return [[MOZUProductVariationDeltaPrice alloc] initWithString:jsonResult error:nil];
	};

	return client;
}

+ (MOZUClient *)clientForAddProductVariationLocalizedPriceOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode body:(MOZUProductVariationFixedPrice *)body productCode:(NSString *)productCode variationKey:(NSString *)variationKey responseFields:(NSString *)responseFields {
	id url = [MOZUProductVariationURLComponents URLComponentsForAddProductVariationLocalizedPriceOperationWithProductCode:productCode variationKey:variationKey responseFields:responseFields];
	id verb = @"POST";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];

	client.body = body;

	client.JSONParser = ^id(NSString *jsonResult) {
		return [[MOZUProductVariationFixedPrice alloc] initWithString:jsonResult error:nil];
	};

	return client;
}


//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

+ (MOZUClient *)clientForUpdateProductVariationLocalizedDeltaPricesOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode body:(NSArray<MOZUProductVariationDeltaPrice> *)body productCode:(NSString *)productCode variationKey:(NSString *)variationKey {
	id url = [MOZUProductVariationURLComponents URLComponentsForUpdateProductVariationLocalizedDeltaPricesOperationWithProductCode:productCode variationKey:variationKey];
	id verb = @"PUT";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];

	client.body = body;

	client.JSONParser = ^id(NSString *jsonResult) {
		NSArray *jsonAsArray = [NSJSONSerialization JSONObjectWithData:[jsonResult dataUsingEncoding:NSUTF8StringEncoding] options:kNilOptions error:nil];
		return [MOZUProductVariationDeltaPrice arrayOfModelsFromDictionaries:jsonAsArray error:nil];
	};

	return client;
}

+ (MOZUClient *)clientForUpdateProductVariationLocalizedDeltaPriceOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode body:(MOZUProductVariationDeltaPrice *)body productCode:(NSString *)productCode variationKey:(NSString *)variationKey currencyCode:(NSString *)currencyCode responseFields:(NSString *)responseFields {
	id url = [MOZUProductVariationURLComponents URLComponentsForUpdateProductVariationLocalizedDeltaPriceOperationWithProductCode:productCode variationKey:variationKey currencyCode:currencyCode responseFields:responseFields];
	id verb = @"PUT";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];

	client.body = body;

	client.JSONParser = ^id(NSString *jsonResult) {
		return [[MOZUProductVariationDeltaPrice alloc] initWithString:jsonResult error:nil];
	};

	return client;
}

+ (MOZUClient *)clientForUpdateProductVariationLocalizedPricesOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode body:(NSArray<MOZUProductVariationFixedPrice> *)body productCode:(NSString *)productCode variationKey:(NSString *)variationKey {
	id url = [MOZUProductVariationURLComponents URLComponentsForUpdateProductVariationLocalizedPricesOperationWithProductCode:productCode variationKey:variationKey];
	id verb = @"PUT";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];

	client.body = body;

	client.JSONParser = ^id(NSString *jsonResult) {
		NSArray *jsonAsArray = [NSJSONSerialization JSONObjectWithData:[jsonResult dataUsingEncoding:NSUTF8StringEncoding] options:kNilOptions error:nil];
		return [MOZUProductVariationFixedPrice arrayOfModelsFromDictionaries:jsonAsArray error:nil];
	};

	return client;
}

+ (MOZUClient *)clientForUpdateProductVariationLocalizedPriceOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode body:(MOZUProductVariationFixedPrice *)body productCode:(NSString *)productCode variationKey:(NSString *)variationKey currencyCode:(NSString *)currencyCode responseFields:(NSString *)responseFields {
	id url = [MOZUProductVariationURLComponents URLComponentsForUpdateProductVariationLocalizedPriceOperationWithProductCode:productCode variationKey:variationKey currencyCode:currencyCode responseFields:responseFields];
	id verb = @"PUT";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];

	client.body = body;

	client.JSONParser = ^id(NSString *jsonResult) {
		return [[MOZUProductVariationFixedPrice alloc] initWithString:jsonResult error:nil];
	};

	return client;
}

+ (MOZUClient *)clientForUpdateProductVariationOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode body:(MOZUProductVariation *)body productCode:(NSString *)productCode variationKey:(NSString *)variationKey responseFields:(NSString *)responseFields {
	id url = [MOZUProductVariationURLComponents URLComponentsForUpdateProductVariationOperationWithProductCode:productCode variationKey:variationKey responseFields:responseFields];
	id verb = @"PUT";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];

	client.body = body;

	client.JSONParser = ^id(NSString *jsonResult) {
		return [[MOZUProductVariation alloc] initWithString:jsonResult error:nil];
	};

	return client;
}

+ (MOZUClient *)clientForUpdateProductVariationsOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode body:(MOZUProductVariationCollection *)body productCode:(NSString *)productCode responseFields:(NSString *)responseFields {
	id url = [MOZUProductVariationURLComponents URLComponentsForUpdateProductVariationsOperationWithProductCode:productCode responseFields:responseFields];
	id verb = @"PUT";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];

	client.body = body;

	client.JSONParser = ^id(NSString *jsonResult) {
		return [[MOZUProductVariationCollection alloc] initWithString:jsonResult error:nil];
	};

	return client;
}


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

+ (MOZUClient *)clientForDeleteProductVariationOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode productCode:(NSString *)productCode variationKey:(NSString *)variationKey {
	id url = [MOZUProductVariationURLComponents URLComponentsForDeleteProductVariationOperationWithProductCode:productCode variationKey:variationKey];
	id verb = @"DELETE";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];

	return client;
}

+ (MOZUClient *)clientForDeleteProductVariationLocalizedDeltaPriceOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode productCode:(NSString *)productCode variationKey:(NSString *)variationKey currencyCode:(NSString *)currencyCode {
	id url = [MOZUProductVariationURLComponents URLComponentsForDeleteProductVariationLocalizedDeltaPriceOperationWithProductCode:productCode variationKey:variationKey currencyCode:currencyCode];
	id verb = @"DELETE";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];

	return client;
}

+ (MOZUClient *)clientForDeleteProductVariationLocalizedPriceOperationWithDataViewMode:(MOZUDataViewMode)dataViewMode productCode:(NSString *)productCode variationKey:(NSString *)variationKey currencyCode:(NSString *)currencyCode {
	id url = [MOZUProductVariationURLComponents URLComponentsForDeleteProductVariationLocalizedPriceOperationWithProductCode:productCode variationKey:variationKey currencyCode:currencyCode];
	id verb = @"DELETE";
	MOZUClient *client = [[MOZUClient alloc] initWithResourceURLComponents:url verb:verb];

	NSString *dataViewModeString = [@(dataViewMode) stringValue];
	[client setHeader:MOZU_X_VOL_DATAVIEW_MODE value:dataViewModeString];

	return client;
}



@end