//
//  Header.h
//  Api
//
//  Created by Sanjay Mandadi on 10/15/13.
//  Copyright (c) 2013 Mozu. All rights reserved.
//

#import <Foundation/Foundation.h>


FOUNDATION_EXPORT NSString* const MOZU_X_VOL_TENANT;
FOUNDATION_EXPORT NSString* const MOZU_X_VOL_SITE;
FOUNDATION_EXPORT NSString* const MOZU_X_VOL_CATALOG;
FOUNDATION_EXPORT NSString* const MOZU_X_VOL_MASTER_CATALOG;
FOUNDATION_EXPORT NSString* const MOZU_X_VOL_SITE_DOMAIN;
FOUNDATION_EXPORT NSString* const MOZU_X_VOL_TENANT_DOMAIN;
FOUNDATION_EXPORT NSString* const MOZU_X_VOL_CORRELATION;
FOUNDATION_EXPORT NSString* const MOZU_X_VOL_HMAC_SHA256;
FOUNDATION_EXPORT NSString* const MOZU_X_VOL_APP_CLAIMS;
FOUNDATION_EXPORT NSString* const MOZU_X_VOL_USER_CLAIMS;
FOUNDATION_EXPORT NSString* const MOZU_X_VOL_VERSION;
FOUNDATION_EXPORT NSString* const MOZU_X_VOL_DATAVIEW_MODE;


