
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "MOZUCommerceProductPropertyValue.h"



@protocol MOZUCommerceProductProperty
@end


@interface MOZUCommerceProductProperty : JSONModel<MOZUCommerceProductProperty>

@property(nonatomic) NSString * attributeFQN;

@property(nonatomic) NSString * dataType;

@property(nonatomic) BOOL isMultiValue;

@property(nonatomic) NSString * name;

@property(nonatomic) NSArray<MOZUCommerceProductPropertyValue> *values;

@end

