
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"



@protocol MOZUSiteSearchPhraseRelevancySettings
@end


@interface MOZUSiteSearchPhraseRelevancySettings : JSONModel<MOZUSiteSearchPhraseRelevancySettings>

@property(nonatomic) NSInteger attributeWeight;

@property(nonatomic) NSInteger descriptionWeight;

@property(nonatomic) NSInteger nameWeight;

@end

