
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "MOZUAttributeVocabularyValue.h"
#import "MOZUProductExtraValueDeltaPrice.h"



@protocol MOZUProductExtraValue
@end


/**
	Properties of a defined value for a product extra attribute.
*/
@interface MOZUProductExtraValue : JSONModel<MOZUProductExtraValue>

/**
The difference between the weight associated with this product extra and the base product. For example, if a product with a monogram weighs an extra 1/4 lb, the DeltaWeight value is "0.25".
*/
@property(nonatomic) NSNumber * deltaWeight;

/**
If true, the value for the product extra is selected by default. Shopper entered extras cannot be defaulted.
*/
@property(nonatomic) NSNumber * isDefaulted;

/**
Properties of a defined value for a product extra attribute.
*/
@property(nonatomic) NSObject * value;

/**
Detail of the product extra attribute vocabulary value.
*/
@property(nonatomic) MOZUAttributeVocabularyValue *attributeVocabularyValueDetail;

/**
The difference between the price associated with this product extra and the base product. For example, if a product with a defined monogram extra costs an additional $10, the DeltaPrice value is "10".
*/
@property(nonatomic) MOZUProductExtraValueDeltaPrice *deltaPrice;

@end

