
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "MOZUProductReservation.h"



@protocol MOZUProductReservationCollection
@end


/**
	A collection of holds placed on product inventory so that the quantities specified are made available for the ordering process.
*/
@interface MOZUProductReservationCollection : JSONModel<MOZUProductReservationCollection>

/**
The number of pages returned based on the startIndex and pageSize supplied. Signed 64-bit (8-byte) integer. System-supplied and read-only.
*/
@property(nonatomic) NSInteger pageCount;

/**
Used to create paged results from a query. Specifies the number of results to display on each page. Maximum: 200.
*/
@property(nonatomic) NSInteger pageSize;

@property(nonatomic) NSInteger startIndex;

/**
The number of the resource entity items listed in the query collection. Signed 64-bit (8-byte) integer. System-supplied and read-only.
*/
@property(nonatomic) NSInteger totalCount;

/**
Container for an array list of properties in a collection.
*/
@property(nonatomic) NSArray<MOZUProductReservation> *items;

@end

