
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"



@protocol MOZUShippingItemRate
@end


/**
	Properties of a shipping rate calculated for a line item in a shipment.
*/
@interface MOZUShippingItemRate : JSONModel<MOZUShippingItemRate>

/**
The calculated shipping amount for an item in a shipment.
*/
@property(nonatomic) NSNumber * amount;

/**
Unique identifier of an item used to calculate or request a shipping rate.
*/
@property(nonatomic) NSString * itemId;

/**
The specified quantity of objects and items. This property is used for numerous object types including products, options, components within a product bundle, cart and order items, returned items, shipping line items, items in a digital product. and items associated with types and reservations.
*/
@property(nonatomic) NSNumber * quantity;

@end

