
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "MOZUShippingRate.h"
#import "MOZUCustomAttribute.h"



@protocol MOZUCarrierRatesResponse
@end


/**
	Arrayed list of calculated shipping rates for the specified carrier.
*/
@interface MOZUCarrierRatesResponse : JSONModel<MOZUCarrierRatesResponse>

/**
Unique identifier of the shipping carrier.
*/
@property(nonatomic) NSString * carrierId;

/**
Array list of calculated shipping rates for the specified carrier.
*/
@property(nonatomic) NSArray<MOZUShippingRate> *shippingRates;

/**
Collection of carrier-specific key-value attribute pairs associated with a shipping carrier. These are required to retrieve a shipping rate request and are returned for the generated shipping label.
*/
@property(nonatomic) NSArray<MOZUCustomAttribute> *customAttributes;

@end

