
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "MOZUAuditInfo.h"
#import "MOZUBillingInfo.h"
#import "MOZUChangeMessage.h"
#import "MOZUPaymentInteraction.h"



@protocol MOZUPayment
@end


/**
	Properties of a payment transaction submitted for an order.
*/
@interface MOZUPayment : JSONModel<MOZUPayment>

/**
The total monetary amount collected in this payment transaction for the order.
*/
@property(nonatomic) NSNumber * amountCollected;

/**
If the payment transaction is a shopper store credit, the total monetary amount credited in this payment transaction for the order.
*/
@property(nonatomic) NSNumber * amountCredited;

/**
The total amount originally requested for this payment.
*/
@property(nonatomic) NSNumber * amountRequested;

/**
Available actions you can complete for an order. These actions may differ depending on the status of the order, such as actions required to enter a payment, return of a package, and fulfillment of a shipment.
*/
@property(nonatomic) NSArray *availableActions;

/**
The external/third party transaction Id for this payment. This is used to store the transaction Id from digital wallet like Visa Checkout
*/
@property(nonatomic) NSString * externalTransactionId;

/**
Unique identifier of the source product property. For a product field it will be the name of the field. For a product attribute it will be the Attribute FQN. 
*/
@property(nonatomic) NSString * id;

/**
Indicates if the product in a cart, order, or wish list is purchased on a recurring schedule. If true, the item can be purchased or fulfilled at regular intervals, such as a monthly billing cycle. For example, digital or physical product subscriptions are recurring cart items. This property is not used at this time and is reserved for future functionality.
*/
@property(nonatomic) BOOL isRecurring;

/**
Unique identifier of the order associated with the payment.
*/
@property(nonatomic) NSString * orderId;

/**
The transaction ID supplied by the payment service to associate with this order payment.
*/
@property(nonatomic) NSString * paymentServiceTransactionId;

/**
The type of payment, such as credit card, check, or PayPal Express. Additional payment types will be supported in future releases.
*/
@property(nonatomic) NSString * paymentType;

/**
The source of data for this payment. By default, this will be set to 'mozu'
*/
@property(nonatomic) NSString * paymentWorkflow;

/**
The current status of an object. This status is specific to the object including payment (New, Authorized, Captured, Declined, Failed, Voided, Credited, CheckRequested, or RolledBack), discount (Active, Scheduled, or Expired), returns (ReturnAuthorized), tenant, package (Fulfilled or NotFulfilled), application, master and product catalogs, orders (Pending, Submitted, Processing, Pending Review, Closed, or Canceled), and order validation results (Pass, Fail, Error, or Review).
*/
@property(nonatomic) NSString * status;

/**
Identifier and datetime stamp information recorded when a user or application creates, updates, or deletes a resource entity. This value is system-supplied and read-only.
*/
@property(nonatomic) MOZUAuditInfo *auditInfo;

/**
Properties for the customer's billing information associated with an order or specific payment.
*/
@property(nonatomic) MOZUBillingInfo *billingInfo;

/**
Collection (list or paged) of change messages logged for each modification made by a shopper to their carts, wishlists, orders, package, payment, pickup, and returns. Change log messages are system-supplied based on shopper actions and read only.
*/
@property(nonatomic) NSArray<MOZUChangeMessage> *changeMessages;

/**
Custom data from payment providers
*/
@property(nonatomic) NSObject * data;

/**
Container for the interactions associated with the payment, which includes details for each action performed for the payment.
*/
@property(nonatomic) NSArray<MOZUPaymentInteraction> *interactions;

@end

