/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUURLComponents.h"

@interface MOZUDocumentTreeURLComponents : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**
Resource Url Components for getTreeDocumentContent
@param documentListName Name of content documentListName to delete
@param documentName The name of the document in the site.
*/
+ (MOZUURLComponents *)URLComponentsForGetTreeDocumentContentOperationWithDocumentListName:(NSString *)documentListName documentName:(NSString *)documentName;

/**
Resource Url Components for transformTreeDocumentContent
@param documentListName Name of content documentListName to delete
@param documentName The name of the document in the site.
@param width 
@param height 
@param max 
@param maxWidth 
@param maxHeight 
@param crop 
@param quality 
*/
+ (MOZUURLComponents *)URLComponentsForTransformTreeDocumentContentOperationWithDocumentListName:(NSString *)documentListName documentName:(NSString *)documentName width:(NSNumber *)width height:(NSNumber *)height max:(NSNumber *)max maxWidth:(NSNumber *)maxWidth maxHeight:(NSNumber *)maxHeight crop:(NSString *)crop quality:(NSNumber *)quality;

/**
Resource Url Components for getTreeDocument
@param documentListName Name of content documentListName to delete
@param documentName The name of the document in the site.
@param includeInactive 
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForGetTreeDocumentOperationWithDocumentListName:(NSString *)documentListName documentName:(NSString *)documentName includeInactive:(NSNumber *)includeInactive responseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark POST Operations
#pragma mark -
//


//
#pragma mark -
#pragma mark PUT Operations
#pragma mark -
//

/**
Resource Url Components for updateTreeDocumentContent
@param documentListName Name of content documentListName to delete
@param documentName The name of the document in the site.
*/
+ (MOZUURLComponents *)URLComponentsForUpdateTreeDocumentContentOperationWithDocumentListName:(NSString *)documentListName documentName:(NSString *)documentName;


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**
Resource Url Components for deleteTreeDocumentContent
@param documentListName Name of content documentListName to delete
@param documentName The name of the document in the site.
*/
+ (MOZUURLComponents *)URLComponentsForDeleteTreeDocumentContentOperationWithDocumentListName:(NSString *)documentListName documentName:(NSString *)documentName;



@end