/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUProductPropertyURL.h"

@implementation MOZUProductPropertyURLComponents

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

+(MOZUURLComponents*)URLComponentsForGetPropertiesOperationWithProductCode:(NSString*)productCode {
	NSString* template = @"/api/commerce/catalog/admin/products/{productCode}/Properties";
	NSDictionary* params = @{
		@"productCode" : productCode,
	};

	return [[MOZUURLComponents alloc] initWithTemplate:template parameters:params location:MOZUTenantPod useSSL:NO];
}

+(MOZUURLComponents*)URLComponentsForGetPropertyOperationWithProductCode:(NSString*)productCode attributeFQN:(NSString*)attributeFQN {
	NSString* template = @"/api/commerce/catalog/admin/products/{productCode}/Properties/{attributeFQN}";
	NSDictionary* params = @{
		@"productCode" : productCode,
		@"attributeFQN" : attributeFQN,
	};

	return [[MOZUURLComponents alloc] initWithTemplate:template parameters:params location:MOZUTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

+(MOZUURLComponents*)URLComponentsForAddPropertyOperationWithProductCode:(NSString*)productCode {
	NSString* template = @"/api/commerce/catalog/admin/products/{productCode}/Properties";
	NSDictionary* params = @{
		@"productCode" : productCode,
	};

	return [[MOZUURLComponents alloc] initWithTemplate:template parameters:params location:MOZUTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

+(MOZUURLComponents*)URLComponentsForUpdatePropertyOperationWithProductCode:(NSString*)productCode attributeFQN:(NSString*)attributeFQN {
	NSString* template = @"/api/commerce/catalog/admin/products/{productCode}/Properties/{attributeFQN}";
	NSDictionary* params = @{
		@"productCode" : productCode,
		@"attributeFQN" : attributeFQN,
	};

	return [[MOZUURLComponents alloc] initWithTemplate:template parameters:params location:MOZUTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

+(MOZUURLComponents*)URLComponentsForDeletePropertyOperationWithProductCode:(NSString*)productCode attributeFQN:(NSString*)attributeFQN {
	NSString* template = @"/api/commerce/catalog/admin/products/{productCode}/Properties/{attributeFQN}";
	NSDictionary* params = @{
		@"productCode" : productCode,
		@"attributeFQN" : attributeFQN,
	};

	return [[MOZUURLComponents alloc] initWithTemplate:template parameters:params location:MOZUTenantPod useSSL:NO];
}



@end