/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUProductOptionURL.h"

@implementation MOZUProductOptionURL

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

+(MOZUURL*)URLForGetOptionsOperationWithProductCode:(NSString*)productCode {
	NSString* template = @"/api/commerce/catalog/admin/products/{productCode}/Options";
	NSDictionary* params = @{
		@"productCode" : productCode,
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}

+(MOZUURL*)URLForGetOptionOperationWithProductCode:(NSString*)productCode attributeFQN:(NSString*)attributeFQN {
	NSString* template = @"/api/commerce/catalog/admin/products/{productCode}/Options/{attributeFQN}";
	NSDictionary* params = @{
		@"productCode" : productCode,
		@"attributeFQN" : attributeFQN,
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

+(MOZUURL*)URLForAddOptionOperationWithProductCode:(NSString*)productCode {
	NSString* template = @"/api/commerce/catalog/admin/products/{productCode}/Options";
	NSDictionary* params = @{
		@"productCode" : productCode,
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

+(MOZUURL*)URLForUpdateOptionOperationWithProductCode:(NSString*)productCode attributeFQN:(NSString*)attributeFQN {
	NSString* template = @"/api/commerce/catalog/admin/products/{productCode}/Options/{attributeFQN}";
	NSDictionary* params = @{
		@"productCode" : productCode,
		@"attributeFQN" : attributeFQN,
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

+(MOZUURL*)URLForDeleteOptionOperationWithProductCode:(NSString*)productCode attributeFQN:(NSString*)attributeFQN {
	NSString* template = @"/api/commerce/catalog/admin/products/{productCode}/Options/{attributeFQN}";
	NSDictionary* params = @{
		@"productCode" : productCode,
		@"attributeFQN" : attributeFQN,
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}



@end