/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUURLComponents.h"

@interface MOZUCustomerAccountURLComponents : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**
Resource Url Components for getAccounts
@param startIndex 
@param pageSize 
@param sortBy 
@param filter A set of filter expressions representing the search parameter syntax when filtering results of a query: eq=equals, ne=not equals, gt=greater than, lt = less than, ge = greater than or equals, le = less than or equals, sw = starts with, or cont = contains. <b>For example: filter=categoryId+eq+12</b>
@param fields The fields to include in the response.
@param q 
@param qLimit 
@param isAnonymous 
*/
+ (MOZUURLComponents *)URLComponentsForGetAccountsOperationWithStartIndex:(NSNumber *)startIndex pageSize:(NSNumber *)pageSize sortBy:(NSString *)sortBy filter:(NSString *)filter fields:(NSString *)fields q:(NSString *)q qLimit:(NSNumber *)qLimit isAnonymous:(NSNumber *)isAnonymous;

/**
Resource Url Components for getAccount
@param accountId Unique identifier of the customer account to retrieve.
*/
+ (MOZUURLComponents *)URLComponentsForGetAccountOperationWithAccountId:(NSInteger)accountId;

/**
Resource Url Components for getLoginState
@param accountId 
*/
+ (MOZUURLComponents *)URLComponentsForGetLoginStateOperationWithAccountId:(NSInteger)accountId;


//
#pragma mark -
#pragma mark POST Operations
#pragma mark -
//

/**
Resource Url Components for addAccount
*/
+ (MOZUURLComponents *)URLComponentsForAddAccountOperation;

/**
Resource Url Components for changePassword
@param accountId 
*/
+ (MOZUURLComponents *)URLComponentsForChangePasswordOperationWithAccountId:(NSInteger)accountId;

/**
Resource Url Components for addLoginToExistingCustomer
@param accountId 
*/
+ (MOZUURLComponents *)URLComponentsForAddLoginToExistingCustomerOperationWithAccountId:(NSInteger)accountId;

/**
Resource Url Components for recomputeCustomerLifetimeValue
@param accountId 
*/
+ (MOZUURLComponents *)URLComponentsForRecomputeCustomerLifetimeValueOperationWithAccountId:(NSInteger)accountId;

/**
Resource Url Components for setLoginLocked
@param accountId 
*/
+ (MOZUURLComponents *)URLComponentsForSetLoginLockedOperationWithAccountId:(NSInteger)accountId;

/**
Resource Url Components for setPasswordChangeRequired
@param accountId 
*/
+ (MOZUURLComponents *)URLComponentsForSetPasswordChangeRequiredOperationWithAccountId:(NSInteger)accountId;

/**
Resource Url Components for addAccountAndLogin
*/
+ (MOZUURLComponents *)URLComponentsForAddAccountAndLoginOperation;

/**
Resource Url Components for addAccounts
*/
+ (MOZUURLComponents *)URLComponentsForAddAccountsOperation;

/**
Resource Url Components for getLoginStateByEmailAddress
@param emailAddress 
*/
+ (MOZUURLComponents *)URLComponentsForGetLoginStateByEmailAddressOperationWithEmailAddress:(NSString *)emailAddress;

/**
Resource Url Components for getLoginStateByUserName
@param userName 
*/
+ (MOZUURLComponents *)URLComponentsForGetLoginStateByUserNameOperationWithUserName:(NSString *)userName;

/**
Resource Url Components for resetPassword
*/
+ (MOZUURLComponents *)URLComponentsForResetPasswordOperation;


//
#pragma mark -
#pragma mark PUT Operations
#pragma mark -
//

/**
Resource Url Components for updateAccount
@param accountId Unique identifier of the customer account.
*/
+ (MOZUURLComponents *)URLComponentsForUpdateAccountOperationWithAccountId:(NSInteger)accountId;


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**
Resource Url Components for deleteAccount
@param accountId Unique identifier of the customer account to delete.
*/
+ (MOZUURLComponents *)URLComponentsForDeleteAccountOperationWithAccountId:(NSInteger)accountId;



@end