/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUURL.h"

@interface MOZUCreditURL : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**
Resource Url for getCredits
@param startIndex When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with a PageSize of 25, to get the 51st through the 75th items, use startIndex=3.
@param pageSize The number of results to display on each page when creating paged results from a query. The maximum value is 200.
@param sortBy The property by which to sort results and whether the results appear in ascending (a-z) order, represented by ASC or in descending (z-a) order, represented by DESC. The sortBy parameter follows an available property. For example: "sortBy=productCode+asc"
@param filter A set of expressions that consist of a field, operator, and value and represent search parameter syntax when filtering results of a query. Valid operators include equals (eq), does not equal (ne), greater than (gt), less than (lt), greater than or equal to (ge), less than or equal to (le), starts with (sw), or contains (cont). For example - "filter=IsDisplayed+eq+true"
*/
+(MOZUURL*)URLForGetCreditsOperationWithStartIndex:(NSNumber*)startIndex pageSize:(NSNumber*)pageSize sortBy:(NSString*)sortBy filter:(NSString*)filter;

/**
Resource Url for getCredit
@param code User-defined code that identifies the store credit to retrieve.
*/
+(MOZUURL*)URLForGetCreditOperationWithCode:(NSString*)code;


//
#pragma mark -
#pragma mark POST Operations
#pragma mark -
//

/**
Resource Url for addCredit
*/
+(MOZUURL*)URLForAddCreditOperation;


//
#pragma mark -
#pragma mark PUT Operations
#pragma mark -
//

/**
Resource Url for updateCredit
@param code User-defined code of the store credit to update.
*/
+(MOZUURL*)URLForUpdateCreditOperationWithCode:(NSString*)code;

/**
Resource Url for associateCreditToShopper
@param code The code that represents the credit to claim for the shopper.
*/
+(MOZUURL*)URLForAssociateCreditToShopperOperationWithCode:(NSString*)code;


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**
Resource Url for deleteCredit
@param code User-defined code of the store credit to delete.
*/
+(MOZUURL*)URLForDeleteCreditOperationWithCode:(NSString*)code;



@end