
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"



@protocol MOZULocalizedContent
@end


/**
	Mozu.SiteSettings.Order.Contracts.LocalizedContent ApiType DOCUMENT_HERE 
*/
@interface MOZULocalizedContent : JSONModel<MOZULocalizedContent>

/**
The two character locale code, per the country code provided. This code determines the localized content to use and display.
*/
@property(nonatomic) NSString * localeCode;

/**
The value of a property, used by numerous objects within Mozu including facets, attributes, products, localized content, metadata, capabilities (Mozu and third-party), location inventory adjustment, and more. The value may be a string, integer, or double. Validation may be run against the entered and saved values depending on the object type.
*/
@property(nonatomic) NSString * value;

@end

