
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "MOZUCatalog.h"



@protocol MOZUTenantMasterCatalog
@end


@interface MOZUTenantMasterCatalog : JSONModel<MOZUTenantMasterCatalog>

@property(nonatomic) NSDate * createDate;

@property(nonatomic) NSString * defaultCurrencyCode;

@property(nonatomic) NSString * defaultLocaleCode;

@property(nonatomic) NSDate * deleteDate;

@property(nonatomic) NSInteger id;

@property(nonatomic) BOOL isDeleted;

@property(nonatomic) NSString * name;

@property(nonatomic) NSString * status;

@property(nonatomic) NSInteger tenantId;

@property(nonatomic) NSDate * updateDate;

@property(nonatomic) NSArray<MOZUCatalog> *catalogs;

@end

