
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "MOZUClient.h"
#import "MOZUAPIContext.h"

#import "MOZUAdminAttributeLocalizedContent.h"


@interface MOZUAttributeLocalizedContentResource : NSObject


@property(readonly, nonatomic) MOZUAPIContext * apiContext;

-(id)initWithAPIContext:(MOZUAPIContext *)apiContext;

-(id)cloneWithAPIContextModification:(MOZUAPIContextModificationBlock)apiContextModification;

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**

@param attributeFQN 
*/

- (void)attributeLocalizedContentsWithAttributeFQN:(NSString *)attributeFQN completionHandler:(void(^)(NSArray<MOZUAdminAttributeLocalizedContent> *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;
/**

@param attributeFQN 
@param localeCode Language used for the entity. Currently, only "en-US" is supported.
@param responseFields Use this field to include those fields which are not included by default.
*/

- (void)attributeLocalizedContentWithAttributeFQN:(NSString *)attributeFQN localeCode:(NSString *)localeCode responseFields:(NSString *)responseFields completionHandler:(void(^)(MOZUAdminAttributeLocalizedContent *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;

//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

/**

@param body 
@param attributeFQN 
@param responseFields Use this field to include those fields which are not included by default.
*/

- (void)addLocalizedContentWithBody:(MOZUAdminAttributeLocalizedContent *)body attributeFQN:(NSString *)attributeFQN responseFields:(NSString *)responseFields completionHandler:(void(^)(MOZUAdminAttributeLocalizedContent *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;

//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

/**

@param body 
@param attributeFQN 
*/

- (void)updateLocalizedContentsWithBody:(NSArray<MOZUAdminAttributeLocalizedContent> *)body attributeFQN:(NSString *)attributeFQN completionHandler:(void(^)(NSArray<MOZUAdminAttributeLocalizedContent> *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;
/**

@param body 
@param attributeFQN 
@param localeCode Language used for the entity. Currently, only "en-US" is supported.
@param responseFields Use this field to include those fields which are not included by default.
*/

- (void)updateLocalizedContentWithBody:(MOZUAdminAttributeLocalizedContent *)body attributeFQN:(NSString *)attributeFQN localeCode:(NSString *)localeCode responseFields:(NSString *)responseFields completionHandler:(void(^)(MOZUAdminAttributeLocalizedContent *result, MOZUAPIError *error, NSHTTPURLResponse *response))handler
;

//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**

@param attributeFQN 
@param localeCode Language used for the entity. Currently, only "en-US" is supported.
*/

- (void)deleteLocalizedContentWithAttributeFQN:(NSString *)attributeFQN localeCode:(NSString *)localeCode completionHandler:(void(^)(MOZUAPIError *error, NSHTTPURLResponse *response))handler
;


@end