
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "MOZUClient.h"
#import "MOZUInStockNotificationSubscription.h"
#import "MOZUInStockNotificationSubscriptionCollection.h"


@interface MOZUInStockNotificationSubscriptionClient : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**

@param filter 
@param pageSize 
@param sortBy 
@param startIndex 
*/

+ (MOZUClient *)clientForGetInStockNotificationSubscriptionsOperationWithStartIndex:(NSNumber *)startIndex pageSize:(NSNumber *)pageSize sortBy:(NSString *)sortBy filter:(NSString *)filter;

/**

@param identifier 
*/

+ (MOZUClient *)clientForGetInStockNotificationSubscriptionOperationWithIdentifier:(NSInteger)identifier;


//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

/**

@param body 
*/

+ (MOZUClient *)clientForAddInStockNotificationSubscriptionOperationWithBody:(MOZUInStockNotificationSubscription *)body;


//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**

@param identifier 
*/

+ (MOZUClient *)clientForDeleteInStockNotificationSubscriptionOperationWithIdentifier:(NSInteger)identifier;



@end