
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "MOZUClient.h"
#import "MOZUAdminAttributeLocalizedContent.h"


@interface MOZUAttributeLocalizedContentClient : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**

@param attributeFQN 
*/

+ (MOZUClient *)clientForGetAttributeLocalizedContentsOperationWithAttributeFQN:(NSString *)attributeFQN;

/**

@param attributeFQN 
@param localeCode Language used for the entity. Currently, only "en-US" is supported.
@param responseFields Use this field to include those fields which are not included by default.
*/

+ (MOZUClient *)clientForGetAttributeLocalizedContentOperationWithAttributeFQN:(NSString *)attributeFQN localeCode:(NSString *)localeCode responseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

/**

@param body 
@param attributeFQN 
@param responseFields Use this field to include those fields which are not included by default.
*/

+ (MOZUClient *)clientForAddLocalizedContentOperationWithBody:(MOZUAdminAttributeLocalizedContent *)body attributeFQN:(NSString *)attributeFQN responseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

/**

@param body 
@param attributeFQN 
*/

+ (MOZUClient *)clientForUpdateLocalizedContentsOperationWithBody:(NSArray<MOZUAdminAttributeLocalizedContent> *)body attributeFQN:(NSString *)attributeFQN;

/**

@param body 
@param attributeFQN 
@param localeCode Language used for the entity. Currently, only "en-US" is supported.
@param responseFields Use this field to include those fields which are not included by default.
*/

+ (MOZUClient *)clientForUpdateLocalizedContentOperationWithBody:(MOZUAdminAttributeLocalizedContent *)body attributeFQN:(NSString *)attributeFQN localeCode:(NSString *)localeCode responseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**

@param attributeFQN 
@param localeCode Language used for the entity. Currently, only "en-US" is supported.
*/

+ (MOZUClient *)clientForDeleteLocalizedContentOperationWithAttributeFQN:(NSString *)attributeFQN localeCode:(NSString *)localeCode;



@end