/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUURL.h"

@interface MOZUProductTypePropertyURL : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**
Resource Url for getProperties
@param productTypeId Identifier of the product type.
*/
+(MOZUURL*)URLForGetPropertiesOperationWithProductTypeId:(NSInteger)productTypeId;

/**
Resource Url for getProperty
@param productTypeId Identifier of the product type.
@param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
*/
+(MOZUURL*)URLForGetPropertyOperationWithProductTypeId:(NSInteger)productTypeId attributeFQN:(NSString*)attributeFQN;


//
#pragma mark -
#pragma mark POST Operations
#pragma mark -
//

/**
Resource Url for addProperty
@param productTypeId Identifier of the product type.
*/
+(MOZUURL*)URLForAddPropertyOperationWithProductTypeId:(NSInteger)productTypeId;


//
#pragma mark -
#pragma mark PUT Operations
#pragma mark -
//

/**
Resource Url for updateProperty
@param productTypeId Identifier of the product type.
@param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
*/
+(MOZUURL*)URLForUpdatePropertyOperationWithProductTypeId:(NSInteger)productTypeId attributeFQN:(NSString*)attributeFQN;


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**
Resource Url for deleteProperty
@param productTypeId Identifier of the product type.
@param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
*/
+(MOZUURL*)URLForDeletePropertyOperationWithProductTypeId:(NSInteger)productTypeId attributeFQN:(NSString*)attributeFQN;



@end