
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUBehavior.h"

@implementation MOZUBehavior
+(BOOL)propertyIsOptional:(NSString*)propertyName
{
	return YES;
}



@end


