/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUFulfillmentInfoURLComponents.h"

@implementation MOZUFulfillmentInfoURLComponents

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

+ (MOZUURLComponents *)URLComponentsForGetFulfillmentInfoOperationWithOrderId:(NSString *)orderId draft:(NSNumber *)draft {
	NSString *template = @"/api/commerce/orders/{orderId}/fulfillmentinfo?draft={draft}";
	NSDictionary *params = @{
		@"orderId" : orderId,
		@"draft" : draft ? draft : @"",
	};

	return [[MOZUURLComponents alloc] initWithTemplate:template parameters:params location:MOZUTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//


//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

+ (MOZUURLComponents *)URLComponentsForSetFulFillmentInfoOperationWithOrderId:(NSString *)orderId updateMode:(NSString *)updateMode version:(NSString *)version {
	NSString *template = @"/api/commerce/orders/{orderId}/fulfillmentinfo?updatemode={updateMode}&version={version}";
	NSDictionary *params = @{
		@"orderId" : orderId,
		@"updateMode" : updateMode ? updateMode : @"",
		@"version" : version ? version : @"",
	};

	return [[MOZUURLComponents alloc] initWithTemplate:template parameters:params location:MOZUTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//



@end