/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUOrderNoteURL.h"

@implementation MOZUOrderNoteURL

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

+(MOZUURL*)URLForGetOrderNotesOperationWithOrderId:(NSString*)orderId {
	NSString* template = @"/api/commerce/orders/{orderId}/notes";
	NSDictionary* params = @{
		@"orderId" : orderId,
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}

+(MOZUURL*)URLForGetOrderNoteOperationWithOrderId:(NSString*)orderId noteId:(NSString*)noteId {
	NSString* template = @"/api/commerce/orders/{orderId}/notes/{noteId}";
	NSDictionary* params = @{
		@"orderId" : orderId,
		@"noteId" : noteId,
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

+(MOZUURL*)URLForCreateOrderNoteOperationWithOrderId:(NSString*)orderId {
	NSString* template = @"/api/commerce/orders/{orderId}/notes";
	NSDictionary* params = @{
		@"orderId" : orderId,
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

+(MOZUURL*)URLForUpdateOrderNoteOperationWithOrderId:(NSString*)orderId noteId:(NSString*)noteId {
	NSString* template = @"/api/commerce/orders/{orderId}/notes/{noteId}";
	NSDictionary* params = @{
		@"orderId" : orderId,
		@"noteId" : noteId,
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

+(MOZUURL*)URLForDeleteOrderNoteOperationWithOrderId:(NSString*)orderId noteId:(NSString*)noteId {
	NSString* template = @"/api/commerce/orders/{orderId}/notes/{noteId}";
	NSDictionary* params = @{
		@"orderId" : orderId,
		@"noteId" : noteId,
	};

	return [[MOZUURL alloc] initWithTemplate:template parameters:params location:kTenantPod useSSL:NO];
}



@end