/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUURLComponents.h"

@interface MOZUPaymentURLComponents : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**
Resource Url Components for getPayments
@param orderId Unique identifier of the order.
*/
+ (MOZUURLComponents *)URLComponentsForGetPaymentsOperationWithOrderId:(NSString *)orderId;

/**
Resource Url Components for getPayment
@param orderId Unique identifier of the order associated with the payment transaction.
@param paymentId Unique identifier of the payment transaction submitted for the order.
*/
+ (MOZUURLComponents *)URLComponentsForGetPaymentOperationWithOrderId:(NSString *)orderId paymentId:(NSString *)paymentId;

/**
Resource Url Components for getAvailablePaymentActions
@param orderId Unique identifier of the order associated with the payment.
@param paymentId Unique identifer of the payment for which to retrieve available actions.
*/
+ (MOZUURLComponents *)URLComponentsForGetAvailablePaymentActionsOperationWithOrderId:(NSString *)orderId paymentId:(NSString *)paymentId;


//
#pragma mark -
#pragma mark POST Operations
#pragma mark -
//

/**
Resource Url Components for performPaymentAction
@param orderId Unique identifier of the order associated with the payment.
@param paymentId Unique identifer of the payment for which to perform the action.
*/
+ (MOZUURLComponents *)URLComponentsForPerformPaymentActionOperationWithOrderId:(NSString *)orderId paymentId:(NSString *)paymentId;

/**
Resource Url Components for createPaymentAction
@param orderId Unique identifier of the order for which to apply the payment.
*/
+ (MOZUURLComponents *)URLComponentsForCreatePaymentActionOperationWithOrderId:(NSString *)orderId;


//
#pragma mark -
#pragma mark PUT Operations
#pragma mark -
//


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//



@end