
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"



@protocol MOZUSearchSynonymSettings
@end


@interface MOZUSearchSynonymSettings : JSONModel<MOZUSearchSynonymSettings>

@property(nonatomic) BOOL expandSynonyms;

@property(nonatomic) NSNumber * mainPartBoost;

@property(nonatomic) NSNumber * synonymPartBoost;

@end

