
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"



@protocol MOZUDocumentInstallation
@end


@interface MOZUDocumentInstallation : JSONModel<MOZUDocumentInstallation>

@property(nonatomic) NSString * documentTypeFQN;

@property(nonatomic) NSString * locale;

@property(nonatomic) NSString * name;

@property(nonatomic) NSObject * properties;

@end

