
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "MOZUClient.h"
#import "MOZUAuthTicket.h"
#import "MOZUCustomerAttribute.h"
#import "MOZUCustomerAttributeCollection.h"


@interface MOZUCustomerAttributeClient : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**
Retrieves the contents of an attribute associated with the specified customer account.
@param accountId Identifier of the customer account associated with the attribute to retrieve.
@param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
*/

+(MOZUClient*)clientForGetAccountAttributeOperationWithAccountId:(NSInteger)accountId attributeFQN:(NSString*)attributeFQN userClaims:(MOZUUserAuthTicket*)userClaims;

/**
Retrieves the list of customer account attributes.
@param accountId Identifier of the customer account associated with the attributes to retrieve.
@param filter 
@param pageSize 
@param sortBy 
@param startIndex 
*/

+(MOZUClient*)clientForGetAccountAttributesOperationWithAccountId:(NSInteger)accountId startIndex:(NSNumber*)startIndex pageSize:(NSNumber*)pageSize sortBy:(NSString*)sortBy filter:(NSString*)filter userClaims:(MOZUUserAuthTicket*)userClaims;


//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

/**
Applies a defined attribute to the customer account specified in the request and assigns a value to the customer attribute.
@param body Properties of the customer account attribute to create.
@param accountId Unique identifier of the customer account.
*/

+(MOZUClient*)clientForAddAccountAttributeOperationWithBody:(MOZUCustomerAttribute*)body accountId:(NSInteger)accountId userClaims:(MOZUUserAuthTicket*)userClaims;


//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

/**
Updates one or more details of a customer account attribute.
@param body The properties of the customer account attribute to update.
@param accountId Identifier of the customer account associated with the attribute.
@param removeMissing If true, remove the items missing from the collection.
*/

+(MOZUClient*)clientForUpdateAccountAttributeOperationWithBody:(MOZUCustomerAttribute*)body accountId:(NSInteger)accountId removeMissing:(NSNumber*)removeMissing userClaims:(MOZUUserAuthTicket*)userClaims;


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//



@end