/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import "MOZUURLComponents.h"

@interface MOZUAttributeLocalizedContentURLComponents : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**
Resource Url Components for getAttributeLocalizedContents
@param attributeFQN 
*/
+ (MOZUURLComponents *)URLComponentsForGetAttributeLocalizedContentsOperationWithAttributeFQN:(NSString *)attributeFQN;

/**
Resource Url Components for getAttributeLocalizedContent
@param attributeFQN 
@param localeCode Language used for the entity. Currently, only "en-US" is supported.
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForGetAttributeLocalizedContentOperationWithAttributeFQN:(NSString *)attributeFQN localeCode:(NSString *)localeCode responseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark POST Operations
#pragma mark -
//

/**
Resource Url Components for addLocalizedContent
@param attributeFQN 
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForAddLocalizedContentOperationWithAttributeFQN:(NSString *)attributeFQN responseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark PUT Operations
#pragma mark -
//

/**
Resource Url Components for updateLocalizedContents
@param attributeFQN 
*/
+ (MOZUURLComponents *)URLComponentsForUpdateLocalizedContentsOperationWithAttributeFQN:(NSString *)attributeFQN;

/**
Resource Url Components for updateLocalizedContent
@param attributeFQN 
@param localeCode Language used for the entity. Currently, only "en-US" is supported.
@param responseFields Use this field to include those fields which are not included by default.
*/
+ (MOZUURLComponents *)URLComponentsForUpdateLocalizedContentOperationWithAttributeFQN:(NSString *)attributeFQN localeCode:(NSString *)localeCode responseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**
Resource Url Components for deleteLocalizedContent
@param attributeFQN 
@param localeCode Language used for the entity. Currently, only "en-US" is supported.
*/
+ (MOZUURLComponents *)URLComponentsForDeleteLocalizedContentOperationWithAttributeFQN:(NSString *)attributeFQN localeCode:(NSString *)localeCode;



@end