
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "MOZUClient.h"
#import "MOZUCartItemCollection.h"
#import "MOZUCartItem.h"
#import "MOZUCart.h"


@interface MOZUCartItemClient : NSObject

//
#pragma mark -
#pragma mark Get Operations
#pragma mark -
//

/**
Retrieves a particular cart item by providing the cart item ID.
@param cartItemId Identifier of the cart item to delete.
@param responseFields Use this field to include those fields which are not included by default.
*/

+ (MOZUClient *)clientForGetCartItemOperationWithCartItemId:(NSString *)cartItemId responseFields:(NSString *)responseFields;

/**
Retrieves a list of cart items including the total number of items in the cart.
@param responseFields Use this field to include those fields which are not included by default.
*/

+ (MOZUClient *)clientForGetCartItemsOperationWithResponseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark Post Operations
#pragma mark -
//

/**
Adds a product to the current shopper's cart.
@param body Properties of an item added to an active shopping cart.
@param responseFields Use this field to include those fields which are not included by default.
*/

+ (MOZUClient *)clientForAddItemToCartOperationWithBody:(MOZUCartItem *)body responseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark Put Operations
#pragma mark -
//

/**
Update the quantity of an individual cart item in the cart of the current shopper.
@param cartItemId Identifier of the cart item to delete.
@param quantity The number of cart items in the shopper's active cart.
@param responseFields Use this field to include those fields which are not included by default.
*/

+ (MOZUClient *)clientForUpdateCartItemQuantityOperationWithCartItemId:(NSString *)cartItemId quantity:(NSInteger)quantity responseFields:(NSString *)responseFields;

/**
Update the product or product quantity of an item in the current shopper's cart.
@param body Properties of an item added to an active shopping cart.
@param cartItemId Identifier of the cart item to delete.
@param responseFields Use this field to include those fields which are not included by default.
*/

+ (MOZUClient *)clientForUpdateCartItemOperationWithBody:(MOZUCartItem *)body cartItemId:(NSString *)cartItemId responseFields:(NSString *)responseFields;


//
#pragma mark -
#pragma mark Delete Operations
#pragma mark -
//

/**
Removes all items in the current shopper's active cart.
*/

+ (MOZUClient *)clientForRemoveAllCartItemsOperation;

/**
Deletes a specific cart item by providing the cart item ID.
@param cartItemId Identifier of the cart item to delete.
*/

+ (MOZUClient *)clientForDeleteCartItemOperationWithCartItemId:(NSString *)cartItemId;



@end