
/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "MOZUOrderValidationMessage.h"



@protocol MOZUOrderValidationResult
@end


/**
	Properties of the resulting order validation performed by an order validation capability.
*/
@interface MOZUOrderValidationResult : JSONModel<MOZUOrderValidationResult>

/**
Date and time when the entity was created, represented in UTC Date/Time.
*/
@property(nonatomic) NSDate * createdDate;

/**
The current status of an object. This status is specific to the object including payment (New, Authorized, Captured, Declined, Failed, Voided, Credited, CheckRequested, or RolledBack), discount (Active, Scheduled, or Expired), returns (ReturnAuthorized), tenant, package (Fulfilled or NotFulfilled), application, master and product catalogs, orders (Pending, Submitted, Processing, Pending Review, Closed, or Canceled), and order validation results (Pass, Fail, Error, or Review).
*/
@property(nonatomic) NSString * status;

/**
Read-only identifier defined by the order validation capability that uniquely identifies this validation operation.
*/
@property(nonatomic) NSString * validationId;

/**
Read-only name of this order validator supplied by the capability.
*/
@property(nonatomic) NSString * validatorName;

/**
The type of order validator supplied by the capability. At this time, the only supported validator type is Fraud.
*/
@property(nonatomic) NSString * validatorType;

/**
Array list of validation and status messages associated with shipping rates, orders, and product purchasable state.
*/
@property(nonatomic) NSArray<MOZUOrderValidationMessage> *messages;

@end

